### ISSUE TITLE
Request to update the noetic and melodic packages to latest?

### ISSUE THREAD

**Issue by seebq** [KumarRobotics/ublox#142]
Was glad to see #136 and excited to get rid of our fork of that very same older repo it was based on, but noticed that the last melodic and/or noetic release is [1.4.1](https://github.com/KumarRobotics/ublox-release#ublox-melodic---141-1).

Could you direct me how to request the ros-build-farm to update re-building for the next melodic and noetic syncs?

@Timple or @clalancette is this easy, I am happy to do it.  Can confirm that current master builds locally and works on a melodic install.

**Comment by Timple** [comment]
https://github.com/ros/rosdistro/pull/30993
https://github.com/ros/rosdistro/pull/30992

The [noetic sync](https://discourse.ros.org/t/new-packages-for-noetic-2021-10-14/22689/3) has just passed, so that will take some weeks. 

Please try the package using the [TestingRepository](http://wiki.ros.org/TestingRepository) to confirm the new functionality works.
